PADV-549 - Disable data sharing consent.
Pearson-Advance/edx-enterprise pull request #8
Opened 2023-06-14 15:35 UTC by anfbermudezme

## Ticket

https://agile-jira.pearson.com/browse/PADV-549

## Description

After the enterprise migration https://agile-jira.pearson.com/browse/PADV-489, it was found that when an enterprise customer has data sharing consent enabled and enterprise-catalog is not enabled, the URL where a new enterprise enrollment is directed leads nowhere. Therefore, in this PR the option to redirect to the enterprise-catalog is disabled and it must be redirected to the expected URL, behavior that we currently have in Juniper, through a site configuration called `DISABLE_DATA_SHARING_CONSENT`.

## Changes Made

- [x] Add feature flag to disable data sharing consent in olive.

2023-06-15 14:31 UTC, Jacatove requested changes

2023-06-15 14:31 UTC, Jacatove commented on enterprise/views.py
> +            ).consent_required()
Could you please try this inline if?, this way we don't indent anything. @anfbermudezme 

```suggestion
        user_consent_needed = get_data_sharing_consent(
            enterprise_customer_user.username,
            enterprise_customer.uuid,
            course_id=course_id,
        ).consent_required() if not configuration_helpers.get_value(
            'DISABLE_DATA_SHARING_CONSENT',
            False,
        ) else False
```

2023-06-15 23:23 UTC, Jacatove approved these changes

2023-06-16 15:10 UTC, Squirrel18 approved these changes

2023-06-16 16:23 UTC, merged