PADV-549-V1 - Disable data sharing consent.
Pearson-Advance/edx-enterprise pull request #9
Opened 2023-06-27 01:53 UTC by anfbermudezme

## Ticket

https://agile-jira.pearson.com/browse/PADV-549

## Description

After reviewing the pull request (PR) at https://github.com/Pearson-Advance/edx-enterprise/pull/8, we have determined that it would be more advantageous to completely disable data sharing consent. Consequently, this PR includes a fix that disables the entire method.

## Changes Made

- [x] Add feature flag to disable data sharing consent in olive.

2023-06-27 15:26 UTC, Jacatove requested changes

2023-06-27 15:26 UTC, Jacatove commented on consent/mixins.py
> +        if configuration_helpers.get_value('DISABLE_DATA_SHARING_CONSENT', False):
What do you think about some logging?

2023-06-27 23:22 UTC, Jacatove approved these changes

2023-06-28 00:18 UTC, Squirrel18 approved these changes

2023-06-28 01:46 UTC, merged